language: node_js
node_js:
  - '0.12'
before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - pip install codecov
after_success:
  - codecov < coverage/cobertura/cobertura-coverage.xml
